-- drop objects
drop table d05_tipo_prodotto cascade constraints;
drop table d05_prodotto cascade constraints;
drop table d05_cliente cascade constraints;
drop table d05_fornitore cascade constraints;
drop table d05_acquisto cascade constraints;
drop table d05_vendita cascade constraints;

-- create tables
create table d05_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d05_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(50 char)
                                   constraint d05_tipo_prodot_tipo_prodo_unq unique not null,
    gruppo                         varchar2(50 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d05_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d05_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d05_prodotto_tipo_prodotto_fk
                                   references d05_tipo_prodotto not null,
    prodotto                       varchar2(50 char) not null,
    prezzo_acquisto                number not null,
    prezzo_vendita                 number not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d05_prodotto_i1 on d05_prodotto (tipo_prodotto_id);

create table d05_cliente (
    id                             number generated by default on null as identity 
                                   constraint d05_cliente_id_pk primary key,
    cliente                        varchar2(50 char)
                                   constraint d05_cliente_cliente_unq unique not null,
    zona                           varchar2(10 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d05_fornitore (
    id                             number generated by default on null as identity 
                                   constraint d05_fornitore_id_pk primary key,
    fornitore                      varchar2(50 char)
                                   constraint d05_fornitore_fornitore_unq unique not null,
    zona                           varchar2(50 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d05_acquisto (
    id                             number generated by default on null as identity 
                                   constraint d05_acquisto_id_pk primary key,
    fornitore_id                   number
                                   constraint d05_acquisto_fornitore_id_fk
                                   references d05_fornitore not null,
    prodotto_id                    number
                                   constraint d05_acquisto_prodotto_id_fk
                                   references d05_prodotto not null,
    data                           date not null,
    quantita                       number not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d05_acquisto_i1 on d05_acquisto (fornitore_id);
create index d05_acquisto_i132 on d05_acquisto (prodotto_id);

create table d05_vendita (
    id                             number generated by default on null as identity 
                                   constraint d05_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d05_vendita_cliente_id_fk
                                   references d05_cliente not null,
    prodotto_id                    number
                                   constraint d05_vendita_prodotto_id_fk
                                   references d05_prodotto not null,
    data                           date not null,
    quantita                       number not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d05_vendita_i1 on d05_vendita (cliente_id);
create index d05_vendita_i182 on d05_vendita (prodotto_id);


-- triggers
create or replace trigger d05_tipo_prodotto_biu
    before insert or update 
    on d05_tipo_prodotto
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_tipo_prodotto_biu;
/

create or replace trigger d05_prodotto_biu
    before insert or update 
    on d05_prodotto
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_prodotto_biu;
/

create or replace trigger d05_cliente_biu
    before insert or update 
    on d05_cliente
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_cliente_biu;
/

create or replace trigger d05_fornitore_biu
    before insert or update 
    on d05_fornitore
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_fornitore_biu;
/

create or replace trigger d05_acquisto_biu
    before insert or update 
    on d05_acquisto
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_acquisto_biu;
/

create or replace trigger d05_vendita_biu
    before insert or update 
    on d05_vendita
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d05_vendita_biu;
/

-- load data
 
-- Generated by Quick SQL Wednesday December 13, 2023  15:10:51
 
/*
tipo prodotto
  tipo prodotto vc50 /nn /unique
  gruppo vc50 /nn

prodotto
  prodotto vc50 /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto_id /nn

cliente
  cliente vc50 /nn /unique
  zona vc10 /nn

fornitore
  fornitore vc50 /nn /unique
  zona vc50 /nn

acquisto
  data d /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn

vendita
  data d /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn

# settings = { prefix: "D05", onDelete: "RESTRICT", semantics: "CHAR", auditCols: true, drop: true, language: "EN", APEX: true }
*/
